global:
  resolve_timeout: 30s

route:
  receiver: discord
  group_by: ["alertname", "service"]
  group_wait: 5s
  group_interval: 15s
  repeat_interval: 2m

receivers:
  - name: discord
    webhook_configs:
      - url: http://discord-webhook:9095/
        send_resolved: true
